public class PlayerDataJSON
{
    public double Coins;
    public double PlayerHP;

    //Level and Wave
    public int Level;
    public int Wave;

    //Date
    public int DayOfYear;
    public int Hour;

    //Armour and Weapon
    public int HelmTier;
    public int ChestplateTier;
    public int GauntletsTier;
    public int LeggingsTier;
    public int BootsTier;
    public int ShieldTier;
    public int WeaponTier;

    //Metals and Alloys
    public double CopperOre;
    public double TinOre;
    public double IronOre;
    public double CoalOre;
    public double AluminiumOre;
    public double NickelOre;
    public double MagnesiumOre;
    public double ZincOre;
    public double LeadOre;
    public double SilverOre;
    public double GoldOre;
    public double PlatinumOre;
    public double ObsidianOre;
    public double MeteoriteOre;
    public double MithrilOre;
    public double AdamanteusOre;
    public double QuicksilverOre;
    public double AetherOre;
    public double CrimsoniteOre;
    public double Copper;
    public double Tin;
    public double Bronze;
    public double Iron;
    public double Steel;
    public double Aluminium;
    public double Duralumin;
    public double Nickel;
    public double Invar;
    public double Magnesium;
    public double Hydronalium;
    public double Zinc;
    public double Brass;
    public double Zamakium;
    public double Lead;
    public double WhiteMetal;
    public double DamascusSteel;
    public double Silver;
    public double Gold;
    public double RoseGold;
    public double Elinvar;
    public double Electrum;
    public double CorinthianBronze;
    public double Platinum;
    public double RefinedObsidian;
    public double Darksteel;
    public double RefinedMeteorite;
    public double MeteoricIron;
    public double Shadowsteel;
    public double MeteoricSteel;
    public double Mithril;
    public double MysticalSteel;
    public double Adamanteus;
    public double DivineSteel;
    public double Quicksilver;
    public double CelestialSteel;
    public double Luminium;
    public double Aether;
    public double Etherium;
    public double CosmicSteel;
    public double Crimsonite;
    public double SoulSteel;
    public double Neutronium;
    public double Orichalcum;
    public double Infinitium;

    //Gems
    public double Amber;
    public double Quartz;
    public double Opal;
    public double Jade;
    public double Cinnabar;
    public double Ametrine;
    public double SmokyQuartz;
    public double Garnet;
    public double Onyx;
    public double Pyrite;
    public double Heliodor;
    public double Citrine;
    public double RoseQuartz;
    public double LapisLazuli;
    public double Aquamarine;
    public double Peridot;
    public double Turquoise;
    public double IcyQuartz;
    public double Coralite;
    public double Amethyst;
    public double Prismarium;
    public double Topaz;
    public double Ruby;
    public double Moonstone;
    public double Sapphire;
    public double Sunstone;
    public double Emerald;
    public double Bloodstone;
    public double StarCrystal;
    public double Diamond;

    //Potions
    public double LuckPotion1;
    public double LuckPotion2;
    public double LuckPotion3;
    public double LuckPotion4;
    public double LuckPotion5;
    public double LuckPotion6;
    public double DefencePotion1;
    public double DefencePotion2;
    public double DefencePotion3;
    public double DefencePotion4;
    public double DefencePotion5;
    public double DefencePotion6;
    public double HealthPotion1;
    public double HealthPotion2;
    public double HealthPotion3;
    public double HealthPotion4;
    public double HealthPotion5;
    public double HealthPotion6;
    public double AttackPotion1;
    public double AttackPotion2;
    public double AttackPotion3;
    public double AttackPotion4;
    public double AttackPotion5;
    public double AttackPotion6;
    public double MagicPotion1;
    public double MagicPotion2;
    public double MagicPotion3;
    public double MagicPotion4;
    public double MagicPotion5;
    public double MagicPotion6;
    public double MarvelousPotion;

    //Herbs
    public double Clover;
    public double DaisyPetal;
    public double Holly;
    public double RoseThorn;
    public double IvySprig;
    public double Windrush;
    public double WillowTwig;
    public double Goosegrass;
    public double Firegrass;
    public double Moly;
    public double Starthistle;
    public double Knotweed;
    public double Bitterroot;
    public double Baneberry;
    public double MandrakeRoot;
    public double TawnymothWeed;
    public double Spleenwort;
    public double HelleboreSyrup;
    public double ValerianRoot;
    public double DragonIvy;
    public double Asphodel;
    public double Wormwood;
    public double Silverweed;
    public double Wolfsbane;
    public double Moondew;
    public double Fluxweed;
    public double Tormentil;
    public double Belladonna;
    public double Nightshade;
    public double Bloodroot;

    //Fruits
    public double RubyApple;
    public double BloodOrange;
    public double CinderBanana;
    public double DewLemon;
    public double GoldenMango;
    public double WildNectarine;

    //Spells
    public double LightningSpell;
    public double WaterSpell;
    public double FireSpell;
    public double WindSpell;
    public double IceSpell;
    public double EarthSpell;
    public double SummoningSpell;
}
